### ISSUE TITLE
Issue test

### ISSUE THREAD

**Issue by ballenabox** [Sakeeri/2021_SE_Team7#2]
Test issue

**Comment by Seongil-Shin** [comment]
1-30 : 상품 삭제를 하였으나, 사용자 뷰에서 그대로 보임
1-37, 1-38 : 상품가격 필터링이 안됨. 따라서 1-38은 세모

**Comment by oh980225** [comment]
## [ISSUE] 공지, 배너관련 이슈 1-4~1-6
1. 이미지가 하나가 생겼다가 사라져다가합니다.
2. 어드민에서 확인해보니 배너 유효기간이 이미 지났는데 이미지가 떠있습니다. (어드민페이지 배너 종료기간 29일 00시 , 현재 시간 29일 21시30분)
3. 처음에는 슬라이드가 될때 이미지가 보였다가 말았다가해서 이미지가 깨진 것 같았는데 또 유효기간이 지나서 그런건가 싶기도 하고 확인이 필요하실 것 같습니다!

**Comment by InHyeok-J** [comment]
## 릴리즈테스팅 이슈 2-1~ 2-23
### 저희가 테스팅할때 구현안된것 및 이슈 적겠습니다. (21.5.29 21시 기준)

2-10: 구현: △  (상품 목록카테고리정보는 있으나 검색 시 검색 키워드 없음.)
2-11: 구현: x   ( 페이지네이션 기준이 몇인지 모르겠으나 다음 페이지로 넘어가지 않음. 확인 불가)
2-12 : 구현 x   (정렬 박스 클릭 시 아무 반응 없음)
2-14 : 구현 x  ( 상품 등록 테스트시 여러 상품 등록도 안되고 실제 상품 페이지에서 여러 이미지 확인 불가)
2-17 : 구현 x  ( 장바구니 정보 관련 기능 없음)
2-19, 2-20: 구현x (장바구니 관련 기능 없음)
2-22, 2-23 구현 x  ( 배송지 관련 기능 없음)

**Comment by ritty27** [comment]
[ISSUE] 배송지 관리, 장바구니
---
2-24 ~ 2-31: 배송지 관리 미구현
2 -32 ~ 2-37 : 회원가입하면 장바구니가 들어가 있고 거기서 수정 불가능
2-38 ~ 2-40 : 상품 이미지 1개만 등록 가능
