### ISSUE TITLE
Release testing 이후 변경사항

### ISSUE THREAD

**Issue by ballenabox** [Sakeeri/2021_SE_Team7#8]
1. 상품 판매정보 페이지를 관리자 페이지에 추가했습니다.
2. 상품 상세정보를 추가했습니다.
3. 삭제 기능(1-30)은 변동이 없습니다. 관리자 페이지에서의 상품 삭제가 사용자 페이지에서의 삭제를 의미하지는 않는다고 판단했습니다.

**Comment by oh980225** [comment]
## 답변
현재 릴리즈테스팅 중인데 2가지 의문이 들었습니다.
1. 구매하기 기능 및 그에 관한 기능이 모두 구현되어 있지 않은데 판매정보 페이지를 어떻게 확인해야할지 의문입니다.
(정말로 이것이 판매 정보를 나타내는 페이지인지에 대한 의문입니다.)
2. 관리자 페이지에서의 삭제는 당연히 사용자 페이지에서도 상품이 보이지 않아야하고 삭제 처리가 됬음을 확인할 수 있어야한다고 생각합니다. 어떤 방식으로 관리자 페이지에서의 상품 삭제를 해석하시고 구현하셨는지 궁금합니다.

**Comment by ballenabox** [comment]
### RE:답변
1. 기능으로 해당 페이지의 존재를 판단한다면 할 말은 없지만, Header/footer 구현사항이라도 건지려고 제목만 붙여서 틀만 만들어놓은 것이라고 생각해주시면 되겠습니다. 
2. 요구사항 문서에서 삭제 기능에 대한 내용은 '관리자 페이지에서 삭제되었다고 표시될 것' 이었습니다. 이 문구 이외에 삭제에 대해 언급한 것은 없었습니다. Validation 방면에서는 낙제점이지만 Verification 방면으로는 넘어갈 수 있는 사항이라고 생각했습니다. 저희 팀의 의견일 뿐이고, 저번 릴리즈 테스팅때에도 따로 이의제기를 하지 않았으니 평가하시는 팀의 의견을 따를 예정입니다.

**Comment by oh980225** [comment]
답변 감사드립니다!
